version: '3.8'

services:
  mcp-server:
    image: jhgaylor/me-mcp-server:main
    container_name: me-mcp-server
    ports:
      - "3000:3000"
    restart: unless-stopped
    # You can either use env_file to load all variables from a file:
    env_file:
      - .env.example
    # Or specify environment variables directly:
    environment:
      # Server configuration
      - HOST=0.0.0.0
      - PORT=3000
      - ENVIRONMENT=production