name: me_mcp_server
description: A MCP server for learning about and interacting with me!
version: 1.0.0
repository: https://github.com/jhgaylor/me_mcp_server

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  mcp_dart: ^0.4.0
  http: ^1.3.0
  yaml: ^3.1.2
  mustache_template: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
